/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "sst-test-langfuse-async-worker-ecs-service-production": {
      "type": "sst.aws.Service"
    }
    "sst-test-langfuse-clickhouse-ecs-service-production": {
      "type": "sst.aws.Service"
    }
    "sst-test-langfuse-web-server-ecs-service-production": {
      "type": "sst.aws.Service"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}