name: setup-pnpm
description: "This is a composite GitHub Action that sets up pnpm, node and installs the project's dependencies."
inputs:
  node_version:
    description: "Node.js version"
    required: true

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 10.6.5

    - name: Setup node ${{ inputs.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        cache: pnpm
        registry-url: "https://npm.pkg.github.com"
        # scope: "@test-workspace"
        env:
          NODE_AUTH_TOKEN: ${{ env.NODE_AUTH_TOKEN }}

    # - name: Get pnpm store directory
    #   shell: bash
    #   run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    # - name: Setup pnpm cache
    #   uses: actions/cache@v4
    #   with:
    #     path: ${{ env.STORE_PATH }}
    #     key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
    #     restore-keys: ${{ runner.os }}-pnpm-store-

    - name: install packages
      run: pnpm install --frozen-lockfile
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ env.NODE_AUTH_TOKEN }}
