name: CI

on:
  push:
    branches:
      - "main"
      - "develop"
      - "qa"
      - "stg"
      - "prd"
    tags-ignore: ['v*']
jobs:
  build:
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache for Turbo
        uses: rharkor/caching-for-turbo@v1.5

      - uses: ./.github/actions/setup-pnpm
        with:
          node_version: 22

      # - name: Lint
      #   run: pnpm format-and-lint

      # - name: Typecheck
      #   run: pnpm typecheck

      # - name: Build
      #   run: pnpm build